### ISSUE TITLE
How to save sip.conf and extensions.conf to another volume?

### ISSUE THREAD

**Issue by sotiris-bos** [andrius/asterisk#12]
Hey! I would like to save my sip and extensions config files somewhere else so that they survive container changes.

Is this possible or something that could be added as a feature?

**Comment by andrius** [comment]
mmm, it is already working, i.e.

docker-compose.yml:
```yaml
services:
  asterisk:
    # ...
    volumes:                                                                                                                                                                         
      - letsencrypt_ssl:/etc/letsencrypt
      - /mnt/data/docker/data/asterisk/spool:/var/spool/asterisk
      - /mnt/data/docker/data/asterisk/log:/var/log/asterisk
      # ...
      - ./asterisk/sip.conf:/etc/asterisk/sip.conf
```

If you want to use docker volume then you could just create a tiny Dockerfile and symlink files, something like this

```dockerfile
FROM andrius/asterisk:VERSION

RUN rm -f /etc/asterisk/sip.conf && \
ln -s /path/to/docker-volume/sip.conf /etc/asterisk/sip.conf
```
